//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5044.27855)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by suyumin at AGSS-ICTNB0035 on 05/28/2015 20:55:13 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace DIYPackaging.Entities
{
    /// <summary>
    /// Represents a row of HotelPrice data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class HotelPrice
    {
        /// <summary>
        /// Gets or sets a int value for the PriceID column.
        /// </summary>
        [DataMember]
        public int PriceID { get; set; }

        /// <summary>
        /// Gets or sets a int value for the HotelID column.
        /// </summary>
        [DataMember]
        public int HotelID { get; set; }

        /// <summary>
        /// Gets or sets a byte value for the HoteRoomTypeID column.
        /// </summary>
        [DataMember]
        public int HoteRoomTypeID { get; set; }

        /// <summary>
        /// Gets or sets a byte value for the CurrencyID column.
        /// </summary>
        [DataMember]
        public int CurrencyID { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the OnlinePriceDate column.
        /// </summary>
        [DataMember]
        public DateTime OnlinePriceDate { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the CheckInDate column.
        /// </summary>
        [DataMember]
        public DateTime CheckInDate { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the OnlinePrice column.
        /// </summary>
        [DataMember]
        public decimal OnlinePrice { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the OfflinePrice column.
        /// </summary>
        [DataMember]
        public decimal OfflinePrice { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CreatedByID column.
        /// </summary>
        [DataMember]
        public int CreatedByID { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the CreatedDate column.
        /// </summary>
        [DataMember]
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Gets or sets a int value for the ModifiedByID column.
        /// </summary>
        [DataMember]
        public int ModifiedByID { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the ModifiedDate column.
        /// </summary>
        [DataMember]
        public DateTime ModifiedDate { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsActive column.
        /// </summary>
        [DataMember]
        public bool IsActive { get; set; }
    }
}
