//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5044.27855)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by suyumin at AGSS-ICTNB0035 on 05/21/2015 20:29:21 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace DIYPackaging.Entities
{
    /// <summary>
    /// Represents a row of Hotel data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class Hotels
    {
        /// <summary>
        /// Gets or sets a int value for the HotelID column.
        /// </summary>
        [DataMember]
        public int HotelID { get; set; }

        /// <summary>
        /// Gets or sets a byte value for the HotelCategoryID column.
        /// </summary>
        [DataMember]
        public int HotelCategoryID { get; set; }

        /// <summary>
        /// Gets or sets a short value for the CountryID column.
        /// </summary>
        [DataMember]
        public short CountryID { get; set; }

        /// <summary>
        /// Gets or sets a int value for the LocationID column.
        /// </summary>
        [DataMember]
        public int LocationID { get; set; }

        /// <summary>
        /// Gets or sets a string value for the HotelCode column.
        /// </summary>
        [DataMember]
        public string HotelCode { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Hotel column.
        /// </summary>
        [DataMember]
        public string Hotel { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Address1 column.
        /// </summary>
        [DataMember]
        public string Address1 { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Address2 column.
        /// </summary>
        [DataMember]
        public string Address2 { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Address3 column.
        /// </summary>
        [DataMember]
        public string Address3 { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Email1 column.
        /// </summary>
        [DataMember]
        public string Email1 { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Email2 column.
        /// </summary>
        [DataMember]
        public string Email2 { get; set; }

        /// <summary>
        /// Gets or sets a string value for the MobilePhone1 column.
        /// </summary>
        [DataMember]
        public string MobilePhone1 { get; set; }

        /// <summary>
        /// Gets or sets a string value for the MobilePhone2 column.
        /// </summary>
        [DataMember]
        public string MobilePhone2 { get; set; }

        /// <summary>
        /// Gets or sets a string value for the OfficePhone1 column.
        /// </summary>
        [DataMember]
        public string OfficePhone1 { get; set; }

        /// <summary>
        /// Gets or sets a string value for the OfficePhone2 column.
        /// </summary>
        [DataMember]
        public string OfficePhone2 { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Fax1 column.
        /// </summary>
        [DataMember]
        public string Fax1 { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Fax2 column.
        /// </summary>
        [DataMember]
        public string Fax2 { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CreatedByID column.
        /// </summary>
        [DataMember]
        public int CreatedByID { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the CreatedDate column.
        /// </summary>
        [DataMember]
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Gets or sets a int value for the ModifiedByID column.
        /// </summary>
        [DataMember]
        public int ModifiedByID { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the ModifiedDate column.
        /// </summary>
        [DataMember]
        public DateTime ModifiedDate { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsOffline column.
        /// </summary>
        [DataMember]
        public bool IsOffline { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsActive column.
        /// </summary>
        [DataMember]
        public bool IsActive { get; set; }
    }
}
