//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5044.27855)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by suyumin at AGSS-ICTNB0035 on 05/28/2015 20:57:18 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace DIYPackaging.Entities
{
    /// <summary>
    /// Represents a row of SupplierContract data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class SupplierContract
    {
        /// <summary>
        /// Gets or sets a int value for the ContractID column.
        /// </summary>
        [DataMember]
        public int ContractID { get; set; }

        /// <summary>
        /// Gets or sets a int value for the SupplierID column.
        /// </summary>
        [DataMember]
        public int SupplierID { get; set; }

        /// <summary>
        /// Gets or sets a string value for the ContractTitle column.
        /// </summary>
        [DataMember]
        public string ContractTitle { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Contract column.
        /// </summary>
        [DataMember]
        public string Contract { get; set; }

        /// <summary>
        /// Gets or sets a string value for the ContractFilePath column.
        /// </summary>
        [DataMember]
        public string ContractFilePath { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the EffectiveStartDate column.
        /// </summary>
        [DataMember]
        public DateTime EffectiveStartDate { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the EffectiveEndDate column.
        /// </summary>
        [DataMember]
        public DateTime EffectiveEndDate { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CreatedByID column.
        /// </summary>
        [DataMember]
        public int CreatedByID { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the CreatedDate column.
        /// </summary>
        [DataMember]
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Gets or sets a int value for the ModifiedByID column.
        /// </summary>
        [DataMember]
        public int ModifiedByID { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the ModifiedDate column.
        /// </summary>
        [DataMember]
        public DateTime ModifiedDate { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsActive column.
        /// </summary>
        [DataMember]
        public bool IsActive { get; set; }
    }
}
