//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5044.27855)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by suyumin at AGSS-ICTNB0035 on 05/28/2015 20:57:18 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace DIYPackaging.Entities
{
    /// <summary>
    /// Represents a row of SupplierType data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class SupplierType
    {
        /// <summary>
        /// Gets or sets a byte value for the SupplierTypeID column.
        /// </summary>
        [DataMember]
        public int SupplierTypeID { get; set; }

        /// <summary>
        /// Gets or sets a string value for the SupplierTypeCode column.
        /// </summary>
        [DataMember]
        public string SupplierTypeCode { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Supplier column.
        /// </summary>
        [DataMember]
        public string Supplier { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CreatedByID column.
        /// </summary>
        [DataMember]
        public int CreatedByID { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the CreatedDate column.
        /// </summary>
        [DataMember]
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Gets or sets a int value for the ModifiedByID column.
        /// </summary>
        [DataMember]
        public int ModifiedByID { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the ModifiedDate column.
        /// </summary>
        [DataMember]
        public DateTime ModifiedDate { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsActive column.
        /// </summary>
        [DataMember]
        public bool IsActive { get; set; }
    }
}
