//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5044.27855)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by suyumin at AGSS-ICTNB0035 on 05/21/2015 20:27:10 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace DIYPackaging.Entities
{
    /// <summary>
    /// Represents a row of Transportation data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class Transportations
    {
        /// <summary>
        /// Gets or sets a int value for the TransportationID column.
        /// </summary>
        [DataMember]
        public int TransportationID { get; set; }

        /// <summary>
        /// Gets or sets a byte value for the TransportTypeID column.
        /// </summary>
        [DataMember]
        public int TransportTypeID { get; set; }

        /// <summary>
        /// Gets or sets a int value for the SupplierID column.
        /// </summary>
        [DataMember]
        public int SupplierID { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Transportation column.
        /// </summary>
        [DataMember]
        public string Transportation { get; set; }

        /// <summary>
        /// Gets or sets a int value for the CreatedByID column.
        /// </summary>
        [DataMember]
        public int CreatedByID { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the CreatedDate column.
        /// </summary>
        [DataMember]
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Gets or sets a int value for the ModifiedByID column.
        /// </summary>
        [DataMember]
        public int ModifiedByID { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the ModifiedDate column.
        /// </summary>
        [DataMember]
        public DateTime ModifiedDate { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsOffline column.
        /// </summary>
        [DataMember]
        public bool IsOffline { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsActive column.
        /// </summary>
        [DataMember]
        public bool IsActive { get; set; }
    }
}
